name: eslint
on:
  push:
    branches:
    - '**'
    paths:
    - '**/*.js'
    - '**/*.tsx'
    - '.github/workflows/eslint.yml'
    - '!node_modules/**'
    tags-ignore:
    - '*'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - name: Use Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '22.x'
          package-manager-cache: false

      - name: Install NPM dependencies
        run: npm ci

      - name: Run eslint
        run: npm run lint
